doctrine:
  dbal:
    dbname: '%env(resolve:DATABASE_NAME)%'
    host: '%env(resolve:DATABASE_HOST)%'
    port: '%env(resolve:DATABASE_PORT)%'
    user: '%env(resolve:DATABASE_USER)%'
    password: '%env(resolve:DATABASE_PASSWORD)%'
    driver: '%env(resolve:DATABASE_DRIVER)%'
    charset: '%env(resolve:DATABASE_CHARSET)%'
    profiling_collect_backtrace: '%kernel.debug%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    connection: default
    mappings:
      App\Write\Product:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Core/Shared/Domain/Entity'
        prefix: 'App\Core\Shared\Domain\Entity'
        alias: App.Core.Shared.Domain.Entity

      #when@test:
#  doctrine:
#    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
#      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
