doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    'DoctrineMigrations': '%kernel.project_dir%/migrations'
    'DoctrineMigrationsWrite': '%kernel.project_dir%/migrations/Write'
    'DoctrineMigrationsRead': '%kernel.project_dir%/migrations/Read'
  enable_profiler: false
