doctrine:
  dbal:
    connections:
      write:
        dbname: '%env(resolve:DATABASE_WRITE_NAME)%'
        host: '%env(resolve:DATABASE_WRITE_HOST)%'
        port: '%env(resolve:DATABASE_WRITE_PORT)%'
        user: '%env(resolve:DATABASE_WRITE_USER)%'
        password: '%env(resolve:DATABASE_WRITE_PASSWORD)%'
        driver: '%env(resolve:DATABASE_WRITE_DRIVER)%'
        charset: '%env(resolve:DATABASE_WRITE_CHARSET)%'
        profiling_collect_backtrace: '%kernel.debug%'
      read:
        dbname: '%env(resolve:DATABASE_READ_NAME)%'
        host: '%env(resolve:DATABASE_READ_HOST)%'
        port: '%env(resolve:DATABASE_READ_PORT)%'
        user: '%env(resolve:DATABASE_READ_USER)%'
        password: '%env(resolve:DATABASE_READ_PASSWORD)%'
        driver: '%env(resolve:DATABASE_READ_DRIVER)%'
        charset: '%env(resolve:DATABASE_READ_CHARSET)%'
        profiling_collect_backtrace: '%kernel.debug%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    entity_managers:
      write:
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        connection: write
        mappings:
          App\Write\Product:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Write/Product/Shared/Domain/Entity'
            prefix: 'App\Write\Product\Shared\Domain\Entity'
            alias: App.Write.Product
      read:
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        connection: read
        mappings:
          App\Read:
            is_bundle: false
            dir: '%kernel.project_dir%/src/Read'
            prefix: 'App\Read'
            alias: App.Read

      #when@test:
#  doctrine:
#    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
#      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
