version: '3.8'
services:
  warehouse_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: api.warehouse.Dockerfile
      args:
        - IMAGE_TAG=${PHP_IMAGE_TAG}
    container_name: shop_api_warehouse
    volumes:
      - ./api/warehouse:/var/www/html
    depends_on:
      - warehouse_db
    command:
      - /var/www/html/scripts/setup.sh

  warehouse_db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: db.warehouse.Dockerfile
      args:
        - IMAGE_TAG=15.4-alpine3.18
    container_name: shop_db_warehouse_write
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${WAREHOUSE_DB_USER}
      - POSTGRES_PASSWORD=${WAREHOUSE_DB_PASSWORD}
      - POSTGRES_DB=${WAREHOUSE_DB_NAME}

  catalog_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: api.catalog.Dockerfile
      args:
        - IMAGE_TAG=${PHP_IMAGE_TAG}
    container_name: shop_api_catalog
    volumes:
      - ./api/catalog:/var/www/html

  availability_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: api.availability.Dockerfile
      args:
        - IMAGE_TAG=${PHP_IMAGE_TAG}
    container_name: shop_api_availability
    volumes:
      - ./api/availability:/var/www/html

  availaibility_redis:
    env_file:
      - .env
    build:
      context: .
      dockerfile: redis.availability.Dockerfile
      args:
        - IMAGE_TAG=${REDIS_IMAGE_TAG}
    container_name: shop_redis_availability

  rabbitmq:
    env_file:
      - .env
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
      args:
        - IMAGE_TAG=${RABBITMQ_IMAGE_TAG}
    container_name: shop_rabbitmq
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  nginx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        - IMAGE_TAG=${NGINX_IMAGE_TAG}
    ports:
      - ${NGINX_WAREHOUSE_EXTERNAL_PORT}:${NGINX_WAREHOUSE_INTERNAL_PORT}
    container_name: shop_nginx