api.products.add:
  controller: App\Core\AddProduct\Presentation\AddProductController::add
  methods: POST
  path: /api/stocks/{stockId}/products

api.products.show:
  controller: App\Core\ShowOneProduct\Presentation\ShowOneProductController::show
  methods: GET
  path: /api/products/{productId}