parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  App\Shared\Infrastructure\Validator\SymfonyValidatorWrapper:
    factory: [ 'App\Shared\Infrastructure\Validator\SymfonyValidatorWrapperFactory', 'create' ]

  App\Write\Shared\Infrastructure\Doctrine\WriteEntityManagerWrapper:
    factory: [ 'App\Write\Shared\Infrastructure\Doctrine\WriteEntityManagerWrapper', 'create' ]

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: true