parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  App\Infrastructure\Validator\SymfonyValidatorWrapper:
    factory: [ 'App\Infrastructure\Validator\SymfonyValidatorWrapperFactory', 'create' ]

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: true

    App\Tests\Stub\:
      resource: '../tests/Stub/'

    App\Tests\DataBuilder\:
      resource: '../tests/DataBuilder/'
