parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  App\Shared\Infrastructure\Validator\SymfonyValidatorWrapper:
    factory: [ 'App\Shared\Infrastructure\Validator\SymfonyValidatorWrapperFactory', 'create' ]

  App\Shared\Infrastructure\Client\GuzzleHttpClient:
    factory: [ 'App\Shared\Infrastructure\Client\GuzzleHttpClientFactory', 'create' ]

  App\Shared\Infrastructure\Client\UrlBuilder:
    arguments:
      - $base: 'http://localhost'
