parameters:
    app.redis.client.host: '%env(REDIS_CLIENT_HOST)%'
    app.redis.client.port: '%env(REDIS_CLIENT_PORT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Shared\Infrastructure\Cache\RedisAdapter:
        factory: ['App\Shared\Infrastructure\Cache\RedisAdapterFactory', 'create']
        arguments: ['%app.redis.client.host%','%app.redis.client.port%','@App\Shared\Infrastructure\Cache\CacheExpirationFactory']

when@test:
    services:
        App\Shared\Infrastructure\Cache\RedisAdapter:
            factory: [ 'App\Shared\Infrastructure\Cache\RedisAdapterFactory', 'create' ]
            arguments: [ '%app.redis.client.host%','%app.redis.client.port%','@App\Shared\Infrastructure\Cache\CacheExpirationFactory' ]
            public: true